version: '3.3'

services:
  # app:
  #   image: "node:lts-alpine"
  #   build:
  #     context: .
  #   user: "node"
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/app/node_modules
  #   env_file:
  #     - .env
  #   ports:
  #     - ${APP_PORT}:3000
  #   tty: true
  #   command: "npm run start"
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - appnet
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    networks:
      - appnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - './.docker/postgres/:/docker-entrypoint-initdb.d/'
  redis:
    image: redis:alpine
    volumes:
      - .docker/redis:/data
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - appnet
    ports:
      - ${REDIS_PORT}:6379
networks:
  appnet:
    driver: bridge
